### ISSUE TITLE
Use Kurbo's BezPath for IR

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#103]
Use https://docs.rs/kurbo/0.1.0/kurbo/struct.BezPath.html. This allows us to define shape reuse in terms of kurbo which I believe is desirable. Further, kurbo already has to/from bezier path which will be handy when compiling from svgs.

**Comment by anthrotype** [comment]
this will also supersede and fix https://github.com/googlefonts/fontmake-rs/issues/33

**Comment by rsheeter** [comment]
^ good catch, will mark as fixing that.
