### ISSUE TITLE
IR handling of cmap

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#145]
@anthrotype had an interesting suggestion in https://github.com/googlefonts/fontmake-rs/pull/134#discussion_r1135299191, copied for convenience:

> actually -- I propose that four our IR we completely do away with the flawed approach of storing a list of unicode codepoints at the Glyph level, and instead have a global CharacterMap (which you can store in the static metadata) that is simply a HashMap<Codepoint, GlyphName>.
> Associating codepoints to a glyph is wrong, not just because it obfuscates the fact that a cmap -- which this piece of data is designed to build -- actually maps from codepoints to glyphs instead of the other way around; but most importantly, it opens the door for ambiguous/invalid/impossible to encode mappings whereby more than one glyph ends up being mapped to the same unicode codepoint (e.g. two glyphs "foo" and "bar" both having unicodes list = [0x0061]; if one types "a", which one will one get, foo or bar?!)
> 
> See discussion on the proposal for storing a global cmap.txt and removing GLIF-level unicode elements in UFO4: https://github.com/unified-font-object/ufo-spec/issues/77

**Comment by rsheeter** [comment]
I believe the counterarguments would be:

1. This moves the IR too far from the source representation, which does store this information on glyphs
1. It doesn't really save any complexity.
   * Because the information lives on glyphs we'd end up adding an IR step that depended on all IR glyphs completion so it could emit the combined map.
   * The only place we need the cmap is the BE cmap task, so it can just do that job

Looking at my own bullets it strikes me that if there are other places than the BE cmap task that need to see the cmap this has appeal.

**Comment by anthrotype** [comment]
> if there are other places than the BE cmap task that need to see the cmap

I don't think there are, cmap is for... cmap :)
It's true that you'll have to read all glyphs to be able to get to the codepoints, because that's where they currently live in the sources..
Let's think about it, maybe revise if the source formats do get changed.

**Comment by khaledhosny** [comment]
Handling variation selectors should be kept in mind as well, I don't know how UFO handles it, but the Glyphs way is [awkward](https://forum.glyphsapp.com/t/unicode-variation-selector-u-fe01/21701).

**Comment by anthrotype** [comment]
UFO has "public.unicodeVariationSequences", implemented in ufo2ft [here](https://github.com/googlefonts/ufo2ft/blob/5b22f201b4650ab9ef1169357702a732e3127a5e/Lib/ufo2ft/outlineCompiler.py#L517-L542).

https://unifiedfontobject.org/versions/ufo3/lib.plist/#publicunicodevariationsequences

**Comment by anthrotype** [comment]
>the Glyphs way is [awkward](https://forum.glyphsapp.com/t/unicode-variation-selector-u-fe01/21701).

OMG.. "You should just add a “.uv002” (the number is the index of the selector starting at FE00 = 1 …) suffix to the alternate glyph."

**Comment by rsheeter** [comment]
Filed #157 to track variation selectors. I think that means there is nothing immediately actionable for cmap so closing. As ever please reopen if I'm wrong.
