### ISSUE TITLE
[fontc] Move more code from binary to lib

### ISSUE THREAD

**Issue by cmyr** [googlefonts/fontmake-rs#162]
Currently much of the code in `fontc` lives in the main.rs file, and I would like to move more of it into the library crate. 

This follows general Rust conventions, and has additional benefits like enforcing visibility on various types, which forces us to think a bit more about our API.

from a brief look, I would expect to move `ChangeDetector` and `Workload` into their own files, along with whatever types they use. Apart from that the other question would be where to put all the free fns. Some of these feel like they should be methods, and maybe the others can just live in their own module, re-exported from the crate root or something?

**Comment by rsheeter** [comment]
Ew ... in looking again it has indeed grown a lot.

Another thing that would be nice to change is to move the dependency declarations to the actual create work functions because that's where we actually know what we need to read/write.

**Comment by rsheeter** [comment]
@cmyr is this now done given your recent changes?
