### ISSUE TITLE
Plumb the vendor id for glyphs and UFO+ds

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#189]
https://github.com/googlefonts/fontmake-rs/pull/184/commits/d6b89f6ea0a830e59aaf0ea69673ed8755010890 hard-codes it to NONE but that's not ultimately what we want.

**Comment by anthrotype** [comment]
UFO fontinfo.plist has `openTypeOS2VendorID`

in Glyphs.app, there's the `vendorID` custom parameter, which I believe was moved to properties in v3.

**Comment by rsheeter** [comment]
I don't seem to see vendor in https://github.com/schriftgestalt/GlyphsSDK/blob/Glyphs3/GlyphsFileFormat/GlyphsFileFormatv3.md#differences-between-version-2?

**Comment by anthrotype** [comment]
in glyphs3 it's a font property whose key is "vendorID", whereas in glyphs2 it is in the customParameters and similarly keyed "vendorID"

**Comment by anthrotype** [comment]
make a New Font, then go to font info tab and in the General section click on the "+" at the top right, search for "Vendor Identification"

Save, and note that "vendorID" is now stored inside properties

**Comment by rsheeter** [comment]
Can reproduce! I guess it's just missing from the v3 doc.

**Comment by rsheeter** [comment]
I guess I might as well implement this now we're talking about it.
