### ISSUE TITLE
Add CI for compiling fonts that pass OTS

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#195]
Either wrap OTS in a crate or use the copy in pip (`(pip install opentype-sanitizer` then `python -m ots some_font.ttf`).

**Comment by anthrotype** [comment]
we don't even need any python or rust wrappers, we can simply curl and unzip the precompiled binaries for ots-sanitize CLI tool which are available on the upstream repo's github releases page:

https://github.com/khaledhosny/ots/releases/tag/v9.0.0
