### ISSUE TITLE
debug and fix a bunch of OTS warnings

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/fontmake-rs#220]
```
$ cargo run -p fontc -- --source resources/testdata/static.designspace
$ python -m ots build/font.ttf
WARNING: bad table directory searchRange
WARNING: bad table directory entrySelector
WARNING: bad table directory rangeShift
WARNING: maxp: Bad maxZones: 0
WARNING: glyf: Number of contour points exceeds maxp maxPoints, adjusting limit.
WARNING: glyf: Number of contour points exceeds maxp maxPoints, adjusting limit.
File sanitized successfully!
```

I think maxp.maxZones should just be 1 by default, that's also [what ufo2ft does](https://github.com/googlefonts/ufo2ft/blob/0f123a791c62ccd09ad41992f6cd52ed21858bc2/Lib/ufo2ft/outlineCompiler.py#L1477).

As for the maxPoints, I think we currently don't set that so it's 0 but the glyf glyphs do contain some points so OTS complains.

The sftn table directory has the searchRange, entrySelector and rangeShift, similar to the ones we have for cmap.
https://learn.microsoft.com/en-us/typography/opentype/spec/otff#table-directory
I'm not sure where these are supposed to be set, I suppose the responsibility is whomever creates the table directory. I guess write-fonts should automatically compute those?

**Comment by rsheeter** [comment]
+1 to write-fonts computing the three table directory fields, preferably automatically or if that's awkward at least providing an API that does it .

**Comment by rsheeter** [comment]
https://github.com/googlefonts/fontations/pull/322 makes FontBuilder set the offending table directory fields.
