### ISSUE TITLE
hmtx for Oswald differs from the one fontmake (py) emits

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#285]
A major source of fontc vs fontmake diffs is hmtx, mostly (though not entirely) due to lsb 0 for some composites:

![image](https://github.com/googlefonts/fontmake-rs/assets/6466432/c9e10bed-6f76-4236-a587-9def291abb1c)

**Comment by rsheeter** [comment]
Seems to be due to ordering issues that are non-obvious courtesy of https://github.com/googlefonts/fontmake-rs/issues/141.

**Comment by rsheeter** [comment]
After #286 biggest issue is some glyphs have different x-min in the rust version. At a glance the Rust version is just wrong, for example a glyph containing `<pt x="15" y="535" on="0"/>` is given `xMin="17"`.

**Comment by rsheeter** [comment]
Looks like we end up calling https://github.com/linebender/kurbo/blob/master/src/param_curve.rs#L214 which is a tighter box than the simple control point box. Per https://learn.microsoft.com/en-us/typography/opentype/spec/glyf#glyph-headers we actually want the cbox.

**Comment by rsheeter** [comment]
See https://github.com/googlefonts/fontmake-rs/pull/286#issuecomment-1553168738 for probable cause of some hmtx entries getting width=0 from fontmake and not from fontc.

**Comment by rsheeter** [comment]
Using unicode data and codepoints I don't seem to get the same answer as fontmake-py for what is/isn't a non-spacing mark. It seems glyphsLib bundles https://github.com/googlefonts/glyphsLib/blob/main/Lib/glyphsLib/data/GlyphData.xml for this.

**Comment by khaledhosny** [comment]
Yes, this and the category/subCategory set in the .glyphs files are the wayy to handle this. Any glyph can be made a mark glyph.
