### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#3]
I think @anthrotype suggested s/ir/font-ir/. To offer an alternative, a fontmake prefix (e.g. fontmake-ir) might make sense?

**Comment by dfrg** [comment]
I’d suggest keeping these short and consistent:
fontir (fir is unfortunately taken on crates)
ufo2fontir
fontc (for the full compiler lib/binary)

fontir has the advantage of sounding like a Tolkienesque weapon

**Comment by rsheeter** [comment]
> fontir has the advantage of sounding like a Tolkienesque weapon

Sold.

**Comment by anthrotype** [comment]
I also like "fontir" without the hyphen 👍

**Comment by kontur** [comment]
Silly "I stumbled into this repo out of curiosity" question... what does the "IR" stand for? It may not be as obvious as you think it is 😅

**Comment by anthrotype** [comment]
https://github.com/googlefonts/oxidize/blob/main/text/2022-11-14-why-ir.md

note this project is still in very early stages so don't expect to find something to work with for the time being :)

**Comment by anthrotype** [comment]
short answer: "intermediate representation"

@kontur check also this out if you're curious https://github.com/googlefonts/oxidize/blob/main/text/2022-11-08-font-compiler-ir.md
