### ISSUE TITLE
Parse Glyphs unicode attributes properly

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#34]
Currently we don't really _use_ the unicode attribute but we will surely need it as we get to things like cmap.

It has more nuances than you'd guess, such as v2 using comma separated unquoted strings.

See https://github.com/googlefonts/fontmake-rs/pull/30#pullrequestreview-1206616519.

**Comment by rsheeter** [comment]
Copying @anthrotype's feedback below:

> actually, a glyph's `unicode` attribute in v2 can contain a comma-separated list of hexadecimal unicode codepoints, not just one.
> 
> And sometimes Georg insisted in not adding quotes to disambiguate these hex strings from equivalent unquoted decimal digits so our openstep_plist parser would give as ints but what they really where was hex strings so we had to work around that...

**Comment by rsheeter** [comment]
Real examples for Google Fonts sources:

```
# v2
Kosugi.glyphs:unicode = 03A2;
Arimo-Regular.glyphs:unicode = "2044,2215";
KiwiMaru-Light.glyphs:unicode = "2ED1,2FA7,9577";

# v3
ReemKufi.glyphs:unicode = (1619,1764);
EulerText.glyphs:unicode = (8260,8725);
```

I don't seem to be seeing examples of decimal in v2 so far.

**Comment by anthrotype** [comment]
> I don't seem to be seeing examples of decimal in v2 so far.

try with this two files I made, one is v2 and the other is v3. 

[1234-unicode-glyphs-v2vs3.zip](https://github.com/googlefonts/fontmake-rs/files/10178973/1234-unicode-glyphs-v2vs3.zip)

specifically the glyph named "see-ethiopic" which has unicode codepoint 0x1234.
In the glyphs v2 source it's written out as unquoted string which should be interpreted as hexadecimal digits:

```
unicode = 1234;
```

whereas in v3 source it's written out as unquoted decimal digits:

```
unicode = 4660;
```

glyphsLib will decode both as 0x1234. We need to support this as well... Do we?

**Comment by anthrotype** [comment]
> there is no decimal in v2 and only decimal in v3?

Correct
