### ISSUE TITLE
Use IndexMap instead of Vec+HashMap?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#54]
StaticMetadata stores an accelerator map plus an ordered vec; coudl just use IndexMap.

See https://github.com/googlefonts/fontmake-rs/pull/43#pullrequestreview-1213452299.

**Comment by rsheeter** [comment]
Doesn't appear to hash which is inconvenient at times but not necessarily a deal breaker

**Comment by anthrotype** [comment]
HashMap is also itself not hashable, in fact we resort to use BTreeMap (hashable) when we want to use a map as a (hashable) key to another map (ir::Glyph.sources map keyed by location)

**Comment by rsheeter** [comment]
After a wild goosechase that boiled down to me wanting to take an approach that is a self-referential datastructure and the compiler being most displeased with that idea - despite it being something that I think _should_ work, and it may under Polonius - I think we do want IndexMap.
