### ISSUE TITLE
What type is Axis min/default/max?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#6]
From https://github.com/googlefonts/fontmake-rs/pull/2#discussion_r1021844201, is f32 the right type?

https://learn.microsoft.com/en-us/typography/opentype/spec/fvar#variationaxisrecord uses fixed. https://fonttools.readthedocs.io/en/latest/designspaceLib/xml.html#axis-element informs us it's a number.

**Comment by dfrg** [comment]
f32 seems to be the correct type given:
1) Most (all?) fonts seems to specify these in integer units of order 1e3
2) We probably don’t want to leak OT specific types into the IR if it can be avoided

**Comment by anthrotype** [comment]
closing as f32 is good
